### ISSUE TITLE
There was is no variation in the Box-Cox parameter in Part 4 "Hands On"

### ISSUE THREAD

**Issue by cwickham** [tidymodels/aml-training#1]
On slide 24/38, the solution to the question: "What was the range of the Box-Cox transformation parameter for Gr_Liv_Area over the resamples?" showed no variation in this parameter.

Turns out all the prepped recipes for all splits have the same parameters because of this line earlier on:
https://github.com/tidymodels/aml-training/blob/56f17a6ff29acd02a1301b8f3c223f84c38d3711/one%20day/code.R#L314

Which gets propagated forward here:
https://github.com/tidymodels/aml-training/blob/56f17a6ff29acd02a1301b8f3c223f84c38d3711/one%20day/code.R#L414

**Comment by topepo** [comment]
Thanks! I moved this over to recipes.
